--nextval('HIBERNATE_SEQUENCE')

INSERT INTO PUBLIC.CATEGORY (ID, DESCRIPTION, NAME) VALUES (nextval('HIBERNATE_SEQUENCE'), 'Component Collection', 'Component Collection');
INSERT INTO PUBLIC.CATEGORY (ID, DESCRIPTION, NAME) VALUES (nextval('HIBERNATE_SEQUENCE'), 'PBC', 'PBC');
INSERT INTO PUBLIC.CATEGORY (ID, DESCRIPTION, NAME) VALUES (nextval('HIBERNATE_SEQUENCE'), 'Solution Template', 'Solution Template');

insert into ORGANISATION (ID, DESCRIPTION, NAME) VALUES (nextval('HIBERNATE_SEQUENCE'), 'Entando', 'Entando');
insert into ORGANISATION (ID, DESCRIPTION, NAME) VALUES (nextval('HIBERNATE_SEQUENCE'), 'Partner 1', 'Partner 1');
