name: My work
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: entando/ent:v7.1.3
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Pack the application
        id: packkk
        env:
          DOCKER_ORG: lcorsettientando
        run: |
          ent bundle build --all --stdout --fail-fast
          rc=$?
          echo "RC $rc"
          if [[ "$rc" -ne 0 ]] ; then
            echo 'TESTS FAILING'; exit $rc
          else
            echo 'TESTS OK'; exit $rc
          fi
        working-directory: ./application
